### ISSUE TITLE
handle_server_url usage causes exception when using instantiate_for_read_access

### ISSUE THREAD

**Issue by TobiasWeigel** [EUDAT-B2SAFE/PYHANDLE#21]
>>> client = PyHandleClient("rest").instantiate_for_read_access(handle_server_url="https://handle.dkrz.de:8003")
INFO:pyhandle.client.resthandleclient:Instantiating RESTHandleClient at 2018-04-13_14:00
INFO:pyhandle.handlesystemconnector:Instantiating HandleSystemConnector
INFO:pyhandle.handlesystemconnector: - handle_server_url set to default: https://hdl.handle.net
INFO:pyhandle.handlesystemconnector: - url_extension_REST_API set to default: /api/handles/
INFO:pyhandle.handlesystemconnector: - https_verify set to default: True
INFO:pyhandle.searcher:Instantiating Searcher
INFO:pyhandle.searcher: - https_verify set to default: True
INFO:pyhandle.searcher: - allowed_search_keys set to default: ['URL', 'CHECKSUM']
INFO:pyhandle.searcher: - solrbaseurl: No default.
INFO:pyhandle.searcher: - reverselookup_url_extension set to default: /hrls/handles/
INFO:pyhandle.searcher: - reverselookup_username: Not specified. No default.
INFO:pyhandle.searcher: - reverselookup_password: Not specified. No default.
INFO:pyhandle.searcher:Reverse lookup not possible. Neither username nor password were provided.
INFO:pyhandle.searcher:Reverse lookup not possible. No URL for reverse lookup provided.
INFO:pyhandle.client.resthandleclient: - HS_ADMIN_permissions set to default: 011111110011
INFO:pyhandle.client.resthandleclient: - modify_HS_ADMIN set to default: False
INFO:pyhandle.client.resthandleclient: - handleowner: Will be set to default for each created handle separately.
INFO:pyhandle.client.resthandleclient:Instantiating RESTHandleClient at 2018-04-13_14:00
INFO:pyhandle.handlesystemconnector:Instantiating HandleSystemConnector
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tobias/virtualenv/lib/python2.7/site-packages/pyhandle/handleclient.py", line 65, in instantiate_for_read_access
    return self.handle_client.instantiate_for_read_access(config)
  File "/home/tobias/virtualenv/lib/python2.7/site-packages/pyhandle/client/resthandleclient.py", line 168, in instantiate_for_read_access
    inst = RESTHandleClient(handle_server_url, **config)
  File "/home/tobias/virtualenv/lib/python2.7/site-packages/pyhandle/client/resthandleclient.py", line 110, in __init__
    self.__handlesystemconnector = HandleSystemConnector(handleclient=self, **args)
  File "/home/tobias/virtualenv/lib/python2.7/site-packages/pyhandle/handlesystemconnector.py", line 79, in __init__
    self.__store_args_or_set_to_defaults(args, defaults)
  File "/home/tobias/virtualenv/lib/python2.7/site-packages/pyhandle/handlesystemconnector.py", line 97, in __store_args_or_set_to_defaults
    LOGGER.info(' - handle_server_url set to '+self.__handle_server_url)
TypeError: cannot concatenate 'str' and 'dict' objects

**Comment by TobiasWeigel** [comment]
Same issue when using no parameters at all:
>>> client = PyHandleClient("rest").instantiate_for_read_access()
INFO:pyhandle.client.resthandleclient:Instantiating RESTHandleClient at 2018-04-13_14:05
INFO:pyhandle.handlesystemconnector:Instantiating HandleSystemConnector
INFO:pyhandle.handlesystemconnector: - handle_server_url set to default: https://hdl.handle.net
INFO:pyhandle.handlesystemconnector: - url_extension_REST_API set to default: /api/handles/
INFO:pyhandle.handlesystemconnector: - https_verify set to default: True
INFO:pyhandle.searcher:Instantiating Searcher
INFO:pyhandle.searcher: - https_verify set to default: True
INFO:pyhandle.searcher: - allowed_search_keys set to default: ['URL', 'CHECKSUM']
INFO:pyhandle.searcher: - solrbaseurl: No default.
INFO:pyhandle.searcher: - reverselookup_url_extension set to default: /hrls/handles/
INFO:pyhandle.searcher: - reverselookup_username: Not specified. No default.
INFO:pyhandle.searcher: - reverselookup_password: Not specified. No default.
INFO:pyhandle.searcher:Reverse lookup not possible. Neither username nor password were provided.
INFO:pyhandle.searcher:Reverse lookup not possible. No URL for reverse lookup provided.
INFO:pyhandle.client.resthandleclient: - HS_ADMIN_permissions set to default: 011111110011
INFO:pyhandle.client.resthandleclient: - modify_HS_ADMIN set to default: False
INFO:pyhandle.client.resthandleclient: - handleowner: Will be set to default for each created handle separately.
INFO:pyhandle.client.resthandleclient:Instantiating RESTHandleClient at 2018-04-13_14:05
INFO:pyhandle.handlesystemconnector:Instantiating HandleSystemConnector
INFO:pyhandle.handlesystemconnector: - handle_server_url set to default: https://hdl.handle.net
INFO:pyhandle.handlesystemconnector: - url_extension_REST_API set to default: /api/handles/
INFO:pyhandle.handlesystemconnector: - https_verify set to default: True
INFO:pyhandle.searcher:Instantiating Searcher
INFO:pyhandle.searcher: - https_verify set to default: True
INFO:pyhandle.searcher: - allowed_search_keys set to default: ['URL', 'CHECKSUM']
INFO:pyhandle.searcher: - solrbaseurl set to same as handle server: {}
INFO:pyhandle.searcher: - reverselookup_url_extension set to default: /hrls/handles/
INFO:pyhandle.searcher: - reverselookup_username: Not specified. No default.
INFO:pyhandle.searcher: - reverselookup_password: Not specified. No default.
INFO:pyhandle.searcher:Reverse lookup not possible. Neither username nor password were provided.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tobias/virtualenv/lib/python2.7/site-packages/pyhandle/handleclient.py", line 65, in instantiate_for_read_access
    return self.handle_client.instantiate_for_read_access(config)
  File "/home/tobias/virtualenv/lib/python2.7/site-packages/pyhandle/client/resthandleclient.py", line 168, in instantiate_for_read_access
    inst = RESTHandleClient(handle_server_url, **config)
  File "/home/tobias/virtualenv/lib/python2.7/site-packages/pyhandle/client/resthandleclient.py", line 111, in __init__
    self.__searcher = Searcher(handleclient=self, **args)
  File "/home/tobias/virtualenv/lib/python2.7/site-packages/pyhandle/searcher.py", line 78, in __init__
    self.__setup_search_access()
  File "/home/tobias/virtualenv/lib/python2.7/site-packages/pyhandle/searcher.py", line 83, in __setup_search_access
    self.__check_and_set_search_access()
  File "/home/tobias/virtualenv/lib/python2.7/site-packages/pyhandle/searcher.py", line 92, in __check_and_set_search_access
    url_exists = self.__check_and_set_search_url()
  File "/home/tobias/virtualenv/lib/python2.7/site-packages/pyhandle/searcher.py", line 121, in __check_and_set_search_url
    self.__reverselookup_baseuri.rstrip('/')+'/'+
AttributeError: 'dict' object has no attribute 'rstrip'

**Comment by SofianeB** [comment]
I can reproduce this with version 1.0.1 but it works with version 1.0.0.

**Comment by SofianeB** [comment]
Fixed by #23 .
